# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo k8s Terraform Azure !
  displayName: 'Run a one-line script'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/azure-terraform/kuebernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$()'''
    backendType: 'azurerm'
    backendServiceArm: 'Azure subscription 1(00c2036d-344b-45e6-a6eb-c70adc70da32)'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageacctaforo255'
    backendAzureRmContainerName: 'storageacctaforo255container'
    backendAzureRmKey: 'Kubernetes-dev.tfstate'
    allowTelemetryCollection: true